name: Docker Build and Push

on:
  push:
    branches:
      - main  # Se ejecutará cuando haya un push en main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Login en Docker Hub
        uses: docker/login-action@v3
        with:
# Hay que configurar los siguientes secretos
# Settings > Secrets and variables > Actions > New repository secret
# DOCKER_USERNAME → Tu usuario de Docker Hub.
# DOCKER_PASSWORD → Tu token de acceso de Docker Hub (en lugar de la contraseña, genera un token en Docker Hub).

          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y etiquetar la imagen
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mi-imagen:latest .
      
      - name: Subir imagen a Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mi-imagen:latest